name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  commit-sha_short:
    description: "commit sha_short"
    value: ${{ steps.get-sha-short.outputs.sha_short }}

runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
    -
      name: Checkout
      uses: actions/checkout@v4
    - name: Set commit SHA
      run: echo "sha_short=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV
      shell: bash
    -
      name: Listing all files in the repository checked out
      run: |
        echo "Listing all files in the repository:"
        ls -la
      shell: bash
